### ISSUE TITLE
Doesn't work with Intellij 15 Ultimate

### ISSUE THREAD

**Issue by sesto** [MoreUnit/org.moreunit.intellij.plugin#4]
Plugin is installed normally without errors, IDE restarts. But when I try to use "Jump To Test" from a class, I want to generate a test for, nothing happens. Windows 7 64 bit

**Comment by ndemengel** [comment]
Hi Sesto,

First, thanks for your report!

Well, everything works fine for me, but I'm not using Windows 7, so maybe the OS plays a role. I will setup a VM to test it.
Meanwhile, could you tell me more about your configuration?
* What's the path to your production and test files in that precise case?
* Which of those files are open  when you trigger the "Jump To Test" action?
* Do you have the message "No test subjects found" displayed?
* Could you jump between those files with IntelliJ 14?
* If those files are new, can you confirm that the plugin doesn't work anymore with a couple of files for which it worked fine under IntelliJ 14?
* Also, when you say "from a class, I want to generate a test for", do you mean that the test class doesn't exist yet, or that you wanted to add a test method to an existing test class? Should the former case be yours, it would be normal since the plugin does not create test classes (but IntelliJ does, for Java classes, using "Go To" > "Test").

I thank you in advance for your answers!

**Comment by sesto** [comment]
I've just switched from Eclipse to IntelliJ 15, I don't know how it would behave in 14.
Indeed, I am trying to generate test, which does not exists. That was perfectly possible with the Eclipse plugin. Now, I am surprised why this functionality is not supported in IntelliJ plugin. I was specifically interested with functionality because it allowed to generate all Mockito boilerplate code in Eclipse. I thought it would be possible to do also in IntelliJ

**Comment by ndemengel** [comment]
That explains a lot :-)

Well, when coding the IntelliJ plugin, our goal was a bit different than with the Eclipse plugin: "stay dead simple and get shit done". Indeed, IDEs already have a lot of features allowing - for instance - to generate test code (IntelliJ live templates are really handy, as are Eclipse code templates). Coding very specific cases took us a lot of time on the Eclipse plugin, and we only ported the key feature to IntelliJ: jumping between files, whatever the language.

I let you read our tiny README for the small set of implemented features.

If you're only coding using Java, you could as well not install MoreUnit, because IntelliJ already has a "Go To > Test" action that jumps between classes, and allows for creating test cases. But I invite you to keep it nonetheless, for the other features :-D
